<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Jiří Tůma</Authors>
    <Company>Olbrasoft</Company>
    <Description>Interface IMarkdownTransformer and Implementation MarkdownTransformer dependent on Markdown and AgilityPack and MarkdownTagHelper</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Olbrasoft/Text</RepositoryUrl>
    <PackageIcon>olbrasoft-text-transformation-markdown.png</PackageIcon>
    <RepositoryType>Git</RepositoryType>
    <PackageTags>Transformation Markdown Html PlainText</PackageTags>
    <Version>10.0.2</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.67" />
    <PackageReference Include="Markdown" Version="2.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net8')) Or $(TargetFramework.StartsWith('net9')) Or $(TargetFramework.StartsWith('net10'))">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\assets\olbrasoft-text-transformation-markdown.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
</Project>